// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';c
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7ZOpYIMuwVC6XITdq2QmJgBKBp0iGcc',
    appId: '1:822246470576:web:b955258bce8ef8d9fe5c75',
    messagingSenderId: '822246470576',
    projectId: 'food-app-94237',
    authDomain: 'food-app-94237.firebaseapp.com',
    storageBucket: 'food-app-94237.appspot.com',
    measurementId: 'G-7P2XEBMMKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWy8ZlLnAPNtbG994V3ZAK_0S_uigf4Q',
    appId: '1:822246470576:android:2d02df5db61203edfe5c75',
    messagingSenderId: '822246470576',
    projectId: 'food-app-94237',
    storageBucket: 'food-app-94237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUg07J4oSzT7ipn8PzAu_7Pfe8YW7C83o',
    appId: '1:822246470576:ios:64c60d8f2383b663fe5c75',
    messagingSenderId: '822246470576',
    projectId: 'food-app-94237',
    storageBucket: 'food-app-94237.appspot.com',
    androidClientId: '822246470576-qp59n2a1dekf15qt5kn3sujejft81bdp.apps.googleusercontent.com',
    iosClientId: '822246470576-4nco0p2n7n682f8lgsl2fhhmcghiljfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUg07J4oSzT7ipn8PzAu_7Pfe8YW7C83o',
    appId: '1:822246470576:ios:64c60d8f2383b663fe5c75',
    messagingSenderId: '822246470576',
    projectId: 'food-app-94237',
    storageBucket: 'food-app-94237.appspot.com',
    androidClientId: '822246470576-qp59n2a1dekf15qt5kn3sujejft81bdp.apps.googleusercontent.com',
    iosClientId: '822246470576-4nco0p2n7n682f8lgsl2fhhmcghiljfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
